plugins {
    id 'java'
}

group = 'nl.framegengine'
version = '1.0-SNAPSHOT'

project.ext.lwjglVersion = "3.3.4"
project.ext.jomlVersion = "1.10.7"
project.ext.lwjglNatives = "natives-macos-arm64"
project.ext.imguiVersion = "1.89.0"

repositories {
    mavenCentral()
}

dependencies {
    implementation platform("org.lwjgl:lwjgl-bom:$lwjglVersion")

    implementation "org.lwjgl:lwjgl"
    implementation "org.lwjgl:lwjgl-assimp"
    implementation "org.lwjgl:lwjgl-bgfx"
    implementation "org.lwjgl:lwjgl-glfw"
    implementation "org.lwjgl:lwjgl-nanovg"
    implementation "org.lwjgl:lwjgl-nuklear"
    implementation "org.lwjgl:lwjgl-openal"
    implementation "org.lwjgl:lwjgl-opengl"
    implementation "org.lwjgl:lwjgl-par"
    implementation "org.lwjgl:lwjgl-stb"
    implementation "org.lwjgl:lwjgl-vulkan"
    implementation "org.lwjgl:lwjgl-nfd"

    implementation 'javax.json:javax.json-api:1.1.4'
    implementation 'org.glassfish:javax.json:1.1.4'
    implementation "org.lwjgl:lwjgl-nfd::$lwjglNatives"
    implementation "org.joml:joml:${jomlVersion}"

    implementation("org.lwjgl:lwjgl-assimp:3.3.4")

    runtimeOnly "org.lwjgl:lwjgl::$lwjglNatives"
    runtimeOnly "org.lwjgl:lwjgl-assimp::$lwjglNatives"
    runtimeOnly "org.lwjgl:lwjgl-bgfx::$lwjglNatives"
    runtimeOnly "org.lwjgl:lwjgl-glfw::$lwjglNatives"
    runtimeOnly "org.lwjgl:lwjgl-nanovg::$lwjglNatives"
    runtimeOnly "org.lwjgl:lwjgl-nuklear::$lwjglNatives"
    runtimeOnly "org.lwjgl:lwjgl-openal::$lwjglNatives"
    runtimeOnly "org.lwjgl:lwjgl-opengl::$lwjglNatives"
    runtimeOnly "org.lwjgl:lwjgl-par::$lwjglNatives"
    runtimeOnly "org.lwjgl:lwjgl-stb::$lwjglNatives"
    runtimeOnly "org.lwjgl:lwjgl-vulkan::$lwjglNatives"

    //ImGUI
    implementation "io.github.spair:imgui-java-binding:$imguiVersion"
    implementation "io.github.spair:imgui-java-lwjgl3:$imguiVersion"
    implementation "io.github.spair:imgui-java-natives-windows:$imguiVersion"
    implementation "io.github.spair:imgui-java-natives-macos:$imguiVersion"
    implementation "io.github.spair:imgui-java-natives-linux:$imguiVersion"

    //Apache IO
    implementation "commons-io:commons-io:2.20.0"
}

test {
    useJUnitPlatform()
}

tasks.register('buildEditorJar', Jar) {
    group = 'build'
    description = 'Build a standalone runnable JAR for the editor.'

    // Set the main class for the manifest
    manifest {
        attributes(
                'Main-Class': 'nl.framegengine.editor.EditorLauncher'  // Replace with your main class
        )
    }

    // Include compiled classes and runtime dependencies
    from sourceSets.main.output

    // Include runtime dependencies (jars)
    dependsOn configurations.runtimeClasspath
    from {
        configurations.runtimeClasspath.collect { it.isDirectory() ? it : zipTree(it) }
    }

    duplicatesStrategy = DuplicatesStrategy.EXCLUDE

    archiveBaseName.set('FrameGengine')
    archiveVersion.set('1.0')
    archiveExtension.set('jar')
}

tasks.register('buildEditor', Exec) {
    group = 'build'
    description = 'Package the editor using jpackage'

    def resourceDir = file('src/main/resources').absolutePath

    // Adjust input/output paths and options as needed
    commandLine 'jpackage',
            '--name', 'FrameGengine Editor',
            '--input', layout.buildDirectory.dir("libs").get().asFile.absolutePath,
            '--main-jar', 'FrameGengine-1.0.jar',
            '--main-class', 'nl.framegengine.editor.EditorLauncher',
            '--resource-dir', resourceDir,
            '--copyright', 'Jenoah Kers',
            '--type', 'app-image',  // 'app-image' or 'dmg' for Mac, 'exe' for Windows installer, etc.
            '--dest', layout.buildDirectory.dir("builtEditor").get().asFile.absolutePath,
            '--icon', "textures/FrameGengine_icon.icns",
            '--java-options', '-XstartOnFirstThread',
            '--verbose'
    dependsOn 'buildEditorJar' // ensure your jar is built before packaging
}

tasks.register('buildStandaloneJar', Jar) {
    group = 'build'
    description = 'Build a standalone runnable JAR for the game.'

    def customProjectPath = project.findProperty("customProjectPath")
    if (!customProjectPath) {
        throw new GradleException("Please set -PcustomProjectPath=/path/to/resources")
    }
    def projectFiles = file(customProjectPath)
    logger.lifecycle("Using project files path: ${projectFiles.absolutePath}")


    manifest {
        attributes('Main-Class': 'nl.framegengine.core.engine.Launcher')
    }

    from sourceSets.main.output
    dependsOn configurations.runtimeClasspath
    from { configurations.runtimeClasspath.collect { it.isDirectory() ? it : zipTree(it) } }

    duplicatesStrategy = DuplicatesStrategy.EXCLUDE

    archiveBaseName.set('FrameGengineGame')
    archiveVersion.set('1.0')
    archiveExtension.set('jar')

    // Include extra resources from a custom directory (e.g., export/resources)
    if (projectFiles.exists()) {
        from(projectFiles) {
            into 'userresource'
        }
    } else {
        logger.info("Project path ${projectFiles.absolutePath} does not exist.")
    }
    logger.lifecycle("Game jar built")

}

tasks.register('buildGame', Exec) {
    group = 'build'
    description = 'Package the application using jpackage'

    def appName = project.findProperty("customAppName") ?: "Your Game"
    def dest = project.findProperty("customDest") ?: layout.buildDirectory.dir("jpackage").get().asFile.absolutePath
    def fileType = project.findProperty("customFileType") ?: "exe"
    def icon = project.findProperty("customIcon") ?: "textures/FrameGengine_icon.ico"
    def gameBuildTmpDir = layout.buildDirectory.dir("Resources").get().asFile

    // Adjust input/output paths and options as needed
    executable 'jpackage'
    args    '--name', appName,
            '--input', layout.buildDirectory.dir("libs").get().asFile.absolutePath,
            '--main-jar', 'FrameGengineGame-1.0.jar',
            '--main-class', 'nl.framegengine.core.engine.Launcher',
            '--type', fileType,  // 'app-image' or 'dmg' for Mac, 'exe' for Windows installer, etc.
            '--dest', dest,
            '--app-content', "\"${gameBuildTmpDir.absolutePath}\"",
            '--icon', icon,
            '--java-options', '-XstartOnFirstThread',
            '--verbose',
            '--java-options', '-Dapp.mode=compiled'
    dependsOn 'buildStandaloneJar' // ensure your jar is built before packaging

    doFirst {
        // Prepare app content here: copy or merge folders into a temp directory
        delete gameBuildTmpDir
        if (!gameBuildTmpDir.exists()) {
            mkdir gameBuildTmpDir
        }
        copy {
            from 'textures'
            into new File(gameBuildTmpDir, "textures")
        }
    }

    doLast {
        delete gameBuildTmpDir // Delete the temporary folder after copying if you want to "move"
    }
}